server:
  port: 8080

spring:
  application:
    name: encryption-demo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Encryption Configuration
# Development: uses default key below
# Production: Set ENCRYPTION_KEY environment variable to override
# Example: export ENCRYPTION_KEY="your-base64-encoded-key-here"
app:
  encryption:
    key: ${ENCRYPTION_KEY:VRYnbfWvjr0j4K9iZDnvjQ==}
    # Enable/disable encryption globally
    enabled: true
    # List of URL patterns that should be encrypted
    # Supports wildcards like /api/*, /user/*, /department/*
    # Supports exact matches like /admin, /health
    encrypted-paths:
      - "/api/*"
      - "/user/*"
      - "/department/*"
      - "/admin/*"

# Logging Configuration
logging:
  level:
    com.example.encryptiondemo: DEBUG
    org.springframework.web: DEBUG

---
# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true

# Production Logging
logging:
  level:
    com.example.encryptiondemo: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

# Production Security Headers
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

# Production Encryption - REQUIRES ENVIRONMENT VARIABLE
# The key is inherited from the default section above
# In production, ENCRYPTION_KEY environment variable must be set
